# Generated by Django 5.1.3 on 2024-12-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('failed_attempt_count', models.IntegerField(default=0)),
                ('attempt_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
