# Generated by Django 5.1.3 on 2024-12-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='attempt_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='failures_since_start',
            field=models.IntegerField(default=1),
        ),
    ]
