# Generated by Django 5.1.3 on 2024-12-11 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_userentitypermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyentityresponse',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='surveyentityresponse',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyentityresponse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.entitys'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('staff', 'الكادر'), ('infrastructure', 'البنية التحتية'), ('systems', 'الأنظمة')], default='systems', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'نص'), ('yes_no', 'نعم/لا'), ('multiple_choice', 'اختيارات متعددة'), ('radio', 'اختيار واحد')], max_length=20),
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.DeleteModel(
            name='SurveyEntityResponse',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
