# Generated by Django 5.1.3 on 2024-12-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_surveyentityresponse_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
