# Generated by Django 5.1.3 on 2024-12-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveys_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='surveys',
            name='is_complete',
        ),
    ]
