# Generated by Django 5.1.3 on 2024-12-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_remove_question_entity_remove_surveys_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
