# Generated by Django 5.1.3 on 2024-12-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='staff_affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
