# Generated by Django 5.1.3 on 2024-12-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_rename_staff_position_question_staff_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='staff_affiliation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_job_title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_role',
        ),
    ]
