# Generated by Django 5.1.3 on 2024-12-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_question_staff_affiliation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='staff_affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='staff_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
