# Generated by Django 5.1.3 on 2024-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_question_staff_affiliation_question_staff_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='staff_affiliation',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_job_title',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='staff_role',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'نص'), ('yes_no', 'نعم/لا'), ('multiple_choice', 'اختيارات متعددة'), ('radio', 'اختيار واحد')], max_length=20),
        ),
    ]
