# Generated by Django 5.1.3 on 2024-12-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FailedLoginAttempt',
        ),
    ]
